import type { FlowConnector, UnitType } from '@src/flowsheet/types'

export type UnitDefinition = {
  unitType: UnitType
  label: string
  tagPrefix: string
  namePrefix: string
  width: number
  height: number
  connectors: FlowConnector[]
}

const materialConnectors: FlowConnector[] = [
  {
    id: 'inlet',
    label: 'Inlet',
    type: 'in',
    direction: 'right',
    x: 0,
    y: 0.5,
    index: 0,
  },
  {
    id: 'outlet',
    label: 'Outlet',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.5,
    index: 0,
  },
]

const energyConnectors: FlowConnector[] = [
  {
    id: 'inlet',
    label: 'Inlet',
    type: 'in',
    direction: 'right',
    x: 0,
    y: 0.5,
    index: 0,
  },
  {
    id: 'outlet',
    label: 'Outlet',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.5,
    index: 0,
  },
]

const oneInOneOutConnectors: FlowConnector[] = [
  {
    id: 'inlet',
    label: 'Inlet',
    type: 'in',
    direction: 'right',
    x: 0,
    y: 0.5,
    index: 0,
  },
  {
    id: 'outlet',
    label: 'Outlet',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.5,
    index: 0,
  },
]

const pumpConnectors: FlowConnector[] = [
  {
    id: 'inlet',
    label: 'Inlet',
    type: 'in',
    direction: 'right',
    x: 0,
    y: 0.5,
    index: 0,
  },
  {
    id: 'energyIn',
    label: 'Energy Stream',
    type: 'energy',
    direction: 'up',
    x: 0.5,
    y: 1,
    index: 1,
  },
  {
    id: 'outlet',
    label: 'Outlet',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.1,
    index: 0,
  },
]

const compressorConnectors: FlowConnector[] = [
  {
    id: 'inlet',
    label: 'Inlet',
    type: 'in',
    direction: 'down',
    x: 0,
    y: 0,
    index: 0,
  },
  {
    id: 'energyIn',
    label: 'Energy Stream',
    type: 'energy',
    direction: 'right',
    x: 0,
    y: 0.5,
    index: 1,
  },
  {
    id: 'outlet',
    label: 'Outlet',
    type: 'out',
    direction: 'up',
    x: 1,
    y: 0.3,
    index: 0,
  },
]

const heatExchangerConnectors: FlowConnector[] = [
  {
    id: 'inlet1',
    label: 'Inlet Stream 1',
    type: 'in',
    direction: 'right',
    x: 0,
    y: 0.5,
    index: 0,
  },
  {
    id: 'inlet2',
    label: 'Inlet Stream 2',
    type: 'in',
    direction: 'down',
    x: 0.5,
    y: 0,
    index: 1,
  },
  {
    id: 'outlet1',
    label: 'Outlet Stream 1',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.5,
    index: 0,
  },
  {
    id: 'outlet2',
    label: 'Outlet Stream 2',
    type: 'out',
    direction: 'down',
    x: 0.5,
    y: 1,
    index: 1,
  },
]

const sideEnergyConnectors: FlowConnector[] = [
  {
    id: 'inlet',
    label: 'Inlet',
    type: 'in',
    direction: 'right',
    x: 0,
    y: 0.5,
    index: 0,
  },
  {
    id: 'energyIn',
    label: 'Energy Stream',
    type: 'energy',
    direction: 'up',
    x: 0.5,
    y: 1,
    index: 1,
  },
  {
    id: 'outlet',
    label: 'Outlet',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.5,
    index: 0,
  },
]

const expanderConnectors: FlowConnector[] = [
  {
    id: 'inlet',
    label: 'Inlet',
    type: 'in',
    direction: 'down',
    x: 0,
    y: 0.3,
    index: 0,
  },
  {
    id: 'energyOut',
    label: 'Energy Stream',
    type: 'energy',
    direction: 'right',
    x: 1,
    y: 0.5,
    index: 1,
  },
  {
    id: 'outlet',
    label: 'Outlet',
    type: 'out',
    direction: 'up',
    x: 1,
    y: 0,
    index: 0,
  },
]

const mixerConnectors: FlowConnector[] = [
  ...Array.from({ length: 6 }, (_, index) => ({
    id: `inlet${index + 1}`,
    label: `Inlet Stream ${index + 1}`,
    type: 'in' as const,
    direction: 'right' as const,
    x: 0,
    y: index / 5,
    index,
  })),
  {
    id: 'outlet',
    label: 'Mixed Stream',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.5,
    index: 0,
  },
]

const splitterConnectors: FlowConnector[] = [
  {
    id: 'inlet',
    label: 'Inlet',
    type: 'in',
    direction: 'right',
    x: 0,
    y: 0.5,
    index: 0,
  },
  ...[0, 0.5, 1].map((y, index) => ({
    id: `outlet${index + 1}`,
    label: `Outlet ${index + 1}`,
    type: 'out' as const,
    direction: 'right' as const,
    x: 1,
    y,
    index,
  })),
]

const coolerConnectors: FlowConnector[] = [
  {
    id: 'inlet',
    label: 'Inlet',
    type: 'in',
    direction: 'right',
    x: 0,
    y: 0.5,
    index: 0,
  },
  {
    id: 'energyIn',
    label: 'Energy Stream (Secondary)',
    type: 'energy',
    direction: 'up',
    x: 0.5,
    y: 0,
    index: 1,
  },
  {
    id: 'outlet',
    label: 'Outlet',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.5,
    index: 0,
  },
]

const separatorVesselConnectors: FlowConnector[] = [
  ...Array.from({ length: 6 }, (_, index) => ({
    id: `inlet${index + 1}`,
    label: `Inlet Stream #${index}`,
    type: 'in' as const,
    direction: 'right' as const,
    x: 0.25,
    y: (index + 2) / 10,
    index,
  })),
  {
    id: 'energyIn',
    label: 'Energy Stream',
    type: 'energy',
    direction: 'right',
    x: 0.25,
    y: 1,
    index: 6,
  },
  {
    id: 'vaporOutlet',
    label: 'Vapor Outlet',
    type: 'out',
    direction: 'up',
    x: 0.5,
    y: 0,
    index: 0,
  },
  {
    id: 'lightLiquidOutlet',
    label: 'Light Liquid Outlet',
    type: 'out',
    direction: 'right',
    x: 0.75,
    y: 5 / 7,
    index: 1,
  },
  {
    id: 'heavyLiquidOutlet',
    label: 'Heavy Liquid Outlet',
    type: 'out',
    direction: 'down',
    x: 0.5,
    y: 1,
    index: 2,
  },
  {
    id: 'reliefOutlet',
    label: 'Relief Valve Outlet',
    type: 'out',
    direction: 'up',
    x: 0.65,
    y: 0.045,
    index: 3,
  },
]

const reactorConnectors: FlowConnector[] = [
  {
    id: 'inlet',
    label: 'Inlet',
    type: 'in',
    direction: 'right',
    x: 0.11,
    y: 0.5,
    index: 0,
  },
  {
    id: 'energyIn',
    label: 'Energy Stream',
    type: 'energy',
    direction: 'up',
    x: 0.11,
    y: 0.7,
    index: 1,
  },
  {
    id: 'vaporOutlet',
    label: 'Vapor Outlet',
    type: 'out',
    direction: 'right',
    x: 0.89,
    y: 0.17,
    index: 0,
  },
  {
    id: 'liquidOutlet',
    label: 'Liquid Outlet',
    type: 'out',
    direction: 'right',
    x: 0.89,
    y: 0.83,
    index: 1,
  },
]

const conversionReactorConnectors: FlowConnector[] = [
  ...reactorConnectors,
  {
    id: 'energyOut',
    label: 'Energy Stream',
    type: 'energy',
    direction: 'down',
    x: 0.5,
    y: 1,
    index: 2,
  },
]

const cstrConnectors: FlowConnector[] = [
  {
    id: 'inlet',
    label: 'Inlet',
    type: 'in',
    direction: 'right',
    x: 0,
    y: 0.5,
    index: 0,
  },
  {
    id: 'energyIn',
    label: 'Energy Stream',
    type: 'energy',
    direction: 'right',
    x: 0.125,
    y: 0.7,
    index: 1,
  },
  {
    id: 'liquidOutlet',
    label: 'Liquid Outlet',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.5,
    index: 0,
  },
  {
    id: 'vaporOutlet',
    label: 'Vapor Outlet (Optional)',
    type: 'out',
    direction: 'up',
    x: 0.5,
    y: 0,
    index: 1,
  },
]

const absorptionColumnConnectors: FlowConnector[] = [
  ...Array.from({ length: 10 }, (_, index) => ({
    id: `feed${index + 1}`,
    label: `Column Feed Port #${index + 1}`,
    type: 'in' as const,
    direction: 'right' as const,
    x: 0.0625,
    y: 0.2 + ((index + 1) / 10) * 0.6,
    index,
  })),
  {
    id: 'topProduct',
    label: 'Top Product',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.02,
    index: 0,
  },
  {
    id: 'bottomProduct',
    label: 'Bottoms Product',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.98,
    index: 1,
  },
  ...Array.from({ length: 8 }, (_, index) => ({
    id: `sideDraw${index + 1}`,
    label: `Side Draw #${index + 1}`,
    type: 'out' as const,
    direction: 'left' as const,
    x: 0.3125,
    y: 0.2 + ((index + 3) / 10) * 0.6,
    index: index + 2,
  })),
]

const distillationColumnConnectors: FlowConnector[] = [
  ...Array.from({ length: 10 }, (_, index) => ({
    id: `feed${index + 1}`,
    label: `Column Feed Port #${index + 1}`,
    type: 'in' as const,
    direction: 'right' as const,
    x: 0.0625,
    y: 0.2 + ((index + 1) / 11) * 0.6,
    index,
  })),
  {
    id: 'reboilerDuty',
    label: 'Reboiler Duty',
    type: 'energy',
    direction: 'left',
    x: 1,
    y: 0.825,
    index: 10,
  },
  {
    id: 'distillate',
    label: 'Distillate',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.3,
    index: 0,
  },
  {
    id: 'bottoms',
    label: 'Bottoms',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.98,
    index: 1,
  },
  ...Array.from({ length: 7 }, (_, index) => ({
    id: `sideDraw${index + 1}`,
    label: `Side Draw #${index + 1}`,
    type: 'out' as const,
    direction: 'left' as const,
    x: 0.3125,
    y: 0.2 + ((index + 3) / 11) * 0.6,
    index: index + 2,
  })),
  {
    id: 'overheadVapor',
    label: 'Overhead Vapor',
    type: 'out',
    direction: 'right',
    x: 1,
    y: 0.02,
    index: 9,
  },
  {
    id: 'condenserDuty',
    label: 'Condenser Duty',
    type: 'energy',
    direction: 'right',
    x: 1,
    y: 0.175,
    index: 10,
  },
]

export const unitRegistry: Record<UnitType, UnitDefinition> = {
  MaterialStream: {
    unitType: 'MaterialStream',
    label: 'Material Stream',
    tagPrefix: '',
    namePrefix: 'MAT',
    width: 96,
    height: 32,
    connectors: materialConnectors,
  },
  EnergyStream: {
    unitType: 'EnergyStream',
    label: 'Energy Stream',
    tagPrefix: 'E',
    namePrefix: 'EN',
    width: 96,
    height: 32,
    connectors: energyConnectors,
  },
  Valve: {
    unitType: 'Valve',
    label: 'Valve',
    tagPrefix: 'VALVE-',
    namePrefix: 'VALV',
    width: 48,
    height: 48,
    connectors: oneInOneOutConnectors,
  },
  Compressor: {
    unitType: 'Compressor',
    label: 'Compressor',
    tagPrefix: 'C-',
    namePrefix: 'COMP',
    width: 58,
    height: 58,
    connectors: compressorConnectors,
  },
  Expander: {
    unitType: 'Expander',
    label: 'Expander',
    tagPrefix: 'EXP-',
    namePrefix: 'EXP',
    width: 58,
    height: 58,
    connectors: expanderConnectors,
  },
  Pump: {
    unitType: 'Pump',
    label: 'Pump',
    tagPrefix: 'PUMP-',
    namePrefix: 'BB',
    width: 58,
    height: 58,
    connectors: pumpConnectors,
  },
  Mixer: {
    unitType: 'Mixer',
    label: 'Stream Mixer',
    tagPrefix: 'MIX-',
    namePrefix: 'MIX',
    width: 64,
    height: 64,
    connectors: mixerConnectors,
  },
  Splitter: {
    unitType: 'Splitter',
    label: 'Stream Splitter',
    tagPrefix: 'SPL-',
    namePrefix: 'SPL',
    width: 64,
    height: 64,
    connectors: splitterConnectors,
  },
  Cooler: {
    unitType: 'Cooler',
    label: 'Cooler',
    tagPrefix: 'COOL-',
    namePrefix: 'COOL',
    width: 58,
    height: 58,
    connectors: coolerConnectors,
  },
  HeatExchanger: {
    unitType: 'HeatExchanger',
    label: 'Heat Exchanger',
    tagPrefix: 'HX-',
    namePrefix: 'HE',
    width: 72,
    height: 72,
    connectors: heatExchangerConnectors,
  },
  Heater: {
    unitType: 'Heater',
    label: 'Heater',
    tagPrefix: 'HEAT-',
    namePrefix: 'HEAT',
    width: 58,
    height: 58,
    connectors: sideEnergyConnectors,
  },
  SeparatorVessel: {
    unitType: 'SeparatorVessel',
    label: 'Gas-Liquid Separator',
    tagPrefix: 'SEP-',
    namePrefix: 'SEP',
    width: 72,
    height: 96,
    connectors: separatorVesselConnectors,
  },
  AbsorptionColumn: {
    unitType: 'AbsorptionColumn',
    label: 'Absorption/Extraction Column',
    tagPrefix: 'ABS-',
    namePrefix: 'ABS',
    width: 88,
    height: 128,
    connectors: absorptionColumnConnectors,
  },
  DistillationColumn: {
    unitType: 'DistillationColumn',
    label: 'Distillation Column',
    tagPrefix: 'COL-',
    namePrefix: 'COL',
    width: 96,
    height: 128,
    connectors: distillationColumnConnectors,
  },
  CSTR: {
    unitType: 'CSTR',
    label: 'CSTR',
    tagPrefix: 'CSTR-',
    namePrefix: 'CSTR',
    width: 72,
    height: 72,
    connectors: cstrConnectors,
  },
  ConversionReactor: {
    unitType: 'ConversionReactor',
    label: 'Conversion Reactor',
    tagPrefix: 'RC-',
    namePrefix: 'RC',
    width: 72,
    height: 72,
    connectors: conversionReactorConnectors,
  },
  EquilibriumReactor: {
    unitType: 'EquilibriumReactor',
    label: 'Equilibrium Reactor',
    tagPrefix: 'RE-',
    namePrefix: 'RE',
    width: 72,
    height: 72,
    connectors: reactorConnectors,
  },
  GibbsReactor: {
    unitType: 'GibbsReactor',
    label: 'Gibbs Reactor',
    tagPrefix: 'RG-',
    namePrefix: 'RG',
    width: 72,
    height: 72,
    connectors: reactorConnectors,
  },
  PFR: {
    unitType: 'PFR',
    label: 'Plug Flow Reactor',
    tagPrefix: 'PFR-',
    namePrefix: 'PFR',
    width: 96,
    height: 48,
    connectors: sideEnergyConnectors,
  },
}

export function getUnitDefinition(unitType: UnitType) {
  return unitRegistry[unitType]
}
