package main

// ConstantProperties is a Go-side canonical compound model modeled after
// DWSIM's ConstantProperties class so different source databases can normalize
// into one typed representation.
type ConstantProperties struct {
	Acentric_Factor                         float64
	BO_BSW                                  float64
	BO_GOR                                  float64
	BO_OilVisc1                             float64
	BO_OilVisc2                             float64
	BO_OilViscTemp1                         float64
	BO_OilViscTemp2                         float64
	BO_PNA_A                                float64
	BO_PNA_N                                float64
	BO_PNA_P                                float64
	BO_SGG                                  float64
	BO_SGO                                  float64
	CAS_Number                              string
	Chao_Seader_Acentricity                 float64
	Chao_Seader_Liquid_Molar_Volume         float64
	Chao_Seader_Solubility_Parameter        float64
	Charge                                  int
	ChemicalStructure                       string
	Comments                                string
	CompCreatorStudyFile                    string
	COSMODBName                             any
	Critical_Compressibility                float64
	Critical_Pressure                       float64
	Critical_Temperature                    float64
	Critical_Volume                         float64
	CurrentDB                               string
	Dipole_Moment                           float64
	Electrolyte_Cp0                         float64
	Electrolyte_DelGF                       float64
	Electrolyte_DelHF                       float64
	EnthalpyOfFusionAtTf                    float64
	Formula                                 string
	HVap_A                                  float64
	HVap_B                                  float64
	HVap_C                                  float64
	HVap_D                                  float64
	HVap_E                                  float64
	HVap_TMAX                               float64
	HVap_TMIN                               float64
	HydrationNumber                         float64
	ID                                      int
	Ideal_Gas_Heat_Capacity_Const_A         float64
	Ideal_Gas_Heat_Capacity_Const_B         float64
	Ideal_Gas_Heat_Capacity_Const_C         float64
	Ideal_Gas_Heat_Capacity_Const_D         float64
	Ideal_Gas_Heat_Capacity_Const_E         float64
	IdealgasCpEquation                      string
	IG_Enthalpy_of_Formation_25C            float64
	IG_Entropy_of_Formation_25C             float64
	IG_Gibbs_Energy_of_Formation_25C        float64
	InChI                                   string
	Ion_CpAq_a                              float64
	Ion_CpAq_b                              float64
	Ion_CpAq_c                              float64
	IsBlackOil                              bool
	IsCOOLPROPSupported                     bool
	IsFPROPSSupported                       bool
	IsHydratedSalt                          bool
	IsHYPO                                  int
	IsIon                                   bool
	IsModified                              bool
	IsPF                                    int
	IsSalt                                  bool
	IsSolid                                 bool
	Liquid_Density_Const_A                  float64
	Liquid_Density_Const_B                  float64
	Liquid_Density_Const_C                  float64
	Liquid_Density_Const_D                  float64
	Liquid_Density_Const_E                  float64
	Liquid_Density_Tmax                     float64
	Liquid_Density_Tmin                     float64
	Liquid_Heat_Capacity_Const_A            float64
	Liquid_Heat_Capacity_Const_B            float64
	Liquid_Heat_Capacity_Const_C            float64
	Liquid_Heat_Capacity_Const_D            float64
	Liquid_Heat_Capacity_Const_E            float64
	Liquid_Heat_Capacity_Tmax               float64
	Liquid_Heat_Capacity_Tmin               float64
	Liquid_Thermal_Conductivity_Const_A     float64
	Liquid_Thermal_Conductivity_Const_B     float64
	Liquid_Thermal_Conductivity_Const_C     float64
	Liquid_Thermal_Conductivity_Const_D     float64
	Liquid_Thermal_Conductivity_Const_E     float64
	Liquid_Thermal_Conductivity_Tmax        float64
	Liquid_Thermal_Conductivity_Tmin        float64
	Liquid_Viscosity_Const_A                float64
	Liquid_Viscosity_Const_B                float64
	Liquid_Viscosity_Const_C                float64
	Liquid_Viscosity_Const_D                float64
	Liquid_Viscosity_Const_E                float64
	LiquidDensityEquation                   string
	LiquidHeatCapacityEquation              string
	LiquidThermalConductivityEquation       string
	LiquidViscosityEquation                 string
	Molar_Weight                            float64
	MolarVolume_k1i                         float64
	MolarVolume_k2i                         float64
	MolarVolume_k3i                         float64
	MolarVolume_v2i                         float64
	MolarVolume_v3i                         float64
	Name                                    string
	NBP                                     *float64
	NegativeIon                             string
	NegativeIonStoichCoeff                  int
	Normal_Boiling_Point                    float64
	OriginalDB                              string
	PC_SAFT_epsilon_k                       float64
	PC_SAFT_m                               float64
	PC_SAFT_sigma                           float64
	PF_MM                                   *float64
	PF_SG                                   *float64
	PF_Tv1                                  *float64
	PF_Tv2                                  *float64
	PF_v1                                   *float64
	PF_v2                                   *float64
	PF_vA                                   *float64
	PF_vB                                   *float64
	PF_Watson_K                             *float64
	PositiveIon                             string
	PositiveIonStoichCoeff                  int
	PR_Volume_Translation_Coefficient       float64
	SMILES                                  string
	Solid_Density_Const_A                   float64
	Solid_Density_Const_B                   float64
	Solid_Density_Const_C                   float64
	Solid_Density_Const_D                   float64
	Solid_Density_Const_E                   float64
	Solid_Density_Tmax                      float64
	Solid_Density_Tmin                      float64
	Solid_Heat_Capacity_Const_A             float64
	Solid_Heat_Capacity_Const_B             float64
	Solid_Heat_Capacity_Const_C             float64
	Solid_Heat_Capacity_Const_D             float64
	Solid_Heat_Capacity_Const_E             float64
	Solid_Heat_Capacity_Tmax                float64
	Solid_Heat_Capacity_Tmin                float64
	SolidDensityAtTs                        float64
	SolidDensityEquation                    string
	SolidHeatCapacityEquation               string
	SolidTs                                 float64
	SRK_Volume_Translation_Coefficient      float64
	StandardStateMolarVolume                float64
	StoichSum                               int
	Surface_Tension_Const_A                 float64
	Surface_Tension_Const_B                 float64
	Surface_Tension_Const_C                 float64
	Surface_Tension_Const_D                 float64
	Surface_Tension_Const_E                 float64
	Surface_Tension_Tmax                    float64
	Surface_Tension_Tmin                    float64
	SurfaceTensionEquation                  string
	TemperatureOfFusion                     float64
	UNIQUAC_Q                               float64
	UNIQUAC_R                               float64
	Vapor_Pressure_Constant_A               float64
	Vapor_Pressure_Constant_B               float64
	Vapor_Pressure_Constant_C               float64
	Vapor_Pressure_Constant_D               float64
	Vapor_Pressure_Constant_E               float64
	Vapor_Pressure_TMAX                     float64
	Vapor_Pressure_TMIN                     float64
	Vapor_Thermal_Conductivity_Const_A      float64
	Vapor_Thermal_Conductivity_Const_B      float64
	Vapor_Thermal_Conductivity_Const_C      float64
	Vapor_Thermal_Conductivity_Const_D      float64
	Vapor_Thermal_Conductivity_Const_E      float64
	Vapor_Thermal_Conductivity_Tmax         float64
	Vapor_Thermal_Conductivity_Tmin         float64
	Vapor_Viscosity_Const_A                 float64
	Vapor_Viscosity_Const_B                 float64
	Vapor_Viscosity_Const_C                 float64
	Vapor_Viscosity_Const_D                 float64
	Vapor_Viscosity_Const_E                 float64
	Vapor_Viscosity_Tmax                    float64
	Vapor_Viscosity_Tmin                    float64
	VaporizationEnthalpyEquation            string
	VaporPressureEquation                   string
	VaporThermalConductivityEquation        string
	VaporViscosityEquation                  string
	Z_Rackett                               float64
	Elements                                map[string]float64
	MODFACGroups                            map[string]int
	NISTMODFACGroups                        map[string]int
	UNIFACGroups                            map[string]int
	FullerDiffusionVolume                   float64
	LennardJonesDiameter                    float64
	LennardJonesEnergy                      float64
	Parachor                                float64
	Tag                                     string
	ExtraProperties                         map[string]any
	COSTALD_SRK_Acentric_Factor             float64
	COSTALD_Characteristic_Volume           float64
	ChemSepFamily                           int
	Vapor_Pressure_Regression_Fit           float64
	Ideal_Gas_Heat_Capacity_Regression_Fit  float64
	Liquid_Viscosity_Regression_Fit         float64
	Liquid_Density_Regression_Fit           float64
	Liquid_Heat_Capacity_Regression_Fit     float64
	Liquid_Thermal_Conductivity_Regression_Fit float64
	Vapor_Thermal_Conductivity_Regression_Fit  float64
	Vapor_Viscosity_Regression_Fit            float64
	Solid_Density_Regression_Fit              float64
	Surface_Tension_Regression_Fit            float64
	Solid_Heat_Capacity_Regression_Fit        float64
	Enthalpy_Of_Vaporization_Regression_Fit   float64
	StandardHeatOfCombustion_LHV              float64
}
